name = "Starry Night Pray"
author = "tEam-StP"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a53ddc937afaa7f378e3815dc38aaa556528b80b2d3bd88c0906d5ee00bc23"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
