name = "Starry Night Pray"
author = "tEam-StP"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68b1ac99c91e41f5ccc6fdb7eb1c7352fe625d6db2c8bddbbb01eefa82c10d73"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
